baseURL = 'http://icdb37.cn'
theme = 'hugo-theme-relearn'
languageCode = "zh-CN"
language = "zh"
defaultContentLanguage = "zh"
title = "随记"
author = "ydbt"

[params]
  # 设置默认语言
  defaultLanguage = "zh"
  # 禁止语言路径
  disableLanguages = true
  # 主题颜色
  themeVariant = ['auto', 'relearn-light', 'relearn-dark']
  [params.author]
    email = 'icdb37@163.com'
    name = 'Liang'

[module]
  [module.hugoVersion]
    min = '0.126.0'

[mediaTypes]
  [mediaTypes.'text/javascript']
    suffixes = ['js']

[outputFormats]
  [outputFormats.print]
    name= 'print'
    baseName = 'index.print'
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  # unused since 7.0.0 but left in here to generate warnings
  [outputFormats.search]
    name= 'search'
    baseName = 'index.searchindex'
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  # unused since 7.0.0 but left in here to generate warnings
  [outputFormats.searchpage]
    name= 'searchpage'
    baseName = 'index.searchpage'
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

[params.relearn.dependencies]
  [params.relearn.dependencies.math]
    name = 'Math'
  [params.relearn.dependencies.mermaid]
    name = 'Mermaid'
  [params.relearn.dependencies.openapi]
    name = 'OpenApi'